using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdventOfCode2018
{
    public class Two
    {
        public static void Part1()
        {
            int twoCounts = 0;
            int threeCounts = 0;
            foreach(string boxID in Input)
            {
                string boxIDLetters = boxID.Distinct().Aggregate("", (s, c) => s = s + c);
                Dictionary<char, int> dict = boxIDLetters.ToDictionary(c => c, c => boxID.Count(c2 => c2 == c));
                if (dict.Any(kvp => kvp.Value == 2)) twoCounts++;
                if (dict.Any(kvp => kvp.Value == 3)) threeCounts++;
            }
            Console.WriteLine($"Checksum is {twoCounts * threeCounts}");

        }

        public static void Part2()
        {
            int len = Input[0].Length;
            for (int i = 0; i < len; i++)
            {
                var candidateList = Input.Select((boxid) =>
                {
                    string frontHalf = "", backHalf = "";
                    if (i < len) backHalf = boxid.Substring(i + 1, len - (i + 1));
                    if (i > 0) frontHalf = boxid.Substring(0, i);
                    return frontHalf + backHalf;
                });

                HashSet<string> hs = new HashSet<string>();
                foreach(string modId in candidateList)
                {
                    if(hs.Contains(modId))
                    {
                        Console.WriteLine($"The common letters in the correct boxIDs are: {modId}");
                        break;
                    }
                    hs.Add(modId);
                }
            }
        }

        public static List<string> InputTest = new List<string>() { "abcdef", "bababc", "abbcde", "abcccd", "aabcdd", "abcdee", "ababab"};
        public static List<string> Input = new List<string>()
        {
"oiwcdpbseqgxryfmlpktnupvza",
"oiwddpbsuqhxryfmlgkznujvza",
"ziwcdpbsechxrvfmlgktnujvza",
"oiwcgpbseqhxryfmmgktnhjvza",
"owwcdpbseqhxryfmlgktnqjvze",
"oiscdkbseqhxrffmlgktnujvza",
"oiwcdibseqoxrnfmlgktnujvza",
"oiwcdpbsejhxryfmlektnujiza",
"oewcdpbsephxryfmlgkwnujvza",
"riwcdpbseqhxryfmlgktnujzaa",
"omwcdpbseqwxryfmlgktnujvqa",
"oiwcdqqneqhxryfmlgktnujvza",
"oawcdvaseqhxryfmlgktnujvza",
"oiwcdabseqhxcyfmlkktnujvza",
"oiwcdpbseqhxryfmlrktrufvza",
"oiwcdpbseqhxdyfmlgqtnujkza",
"oiwcdpbseqhxrmfolgktnujvzy",
"oiwcdpeseqhxnyfmlgktnejvza",
"oiwcdpbseqhxrynmlaktlujvza",
"oiwcdpbseqixryfmlektncjvza",
"liwtdpbseqhxryfylgktnujvza",
"ouwcdpbszqhxryfmlgktnajvza",
"oiwzdpbseqhxryfmngktnujvga",
"wiwcfpbseqhxryfmlgktnuhvza",
"oiwcdpbselhfryfmlrktnujvza",
"oywcdpbveqhxryfmlgktnujdza",
"oiwcdpbsiqhxryfmqiktnujvza",
"obwcdhbseqhxryfmlgktnujvqa",
"oitcdpbseqhfryfmlyktnujvza",
"oiwcdpbseqhxryfmlnutnujqza",
"oiwcdpbseqhxnyfmlhktnujtza",
"oiwcdpbseqhbryfmlgkunuwvza",
"oiwcopbseqhiryfmlgktnkjvza",
"oiwcdpsseqhxryfklrktnujvza",
"oiwcdpsrsqhxryfmlgktnujvza",
"oiwcdpbsyqrxryfmlgktnujvzc",
"ojwcepbseqhxryfmlgktnujvfa",
"oiwcdpbseqhxrlfmlgvtnujvzr",
"oiycdpbsethsryfmlgktnujvza",
"eiwcdpbseqwxryfmlgktnujcza",
"oiocdpbseqhxryfxlgktaujvza",
"qiwydpbseqhpryfmlgktnujvza",
"ziwcdpbseqhxryfmlgktsuuvza",
"oiwcdpbseqheryfmygxtnujvza",
"oiwidpbseqhxryfulgktnujvzm",
"oiscdpdseqhxryfmlgktnujvya",
"oiwmypbseqhxryfmlgktnuxvza",
"oizcwbbseqhxryfmlgktnujvza",
"oiwcdpbseqpxryfmlgxfnujvza",
"oiwpdpbscqhxryxmlgktnujvza",
"oiwcdpbseqhxrifrlgkxnujvza",
"oiwcdpbsrqhxrifmlgktnzjvza",
"tiwcdpbseqhxryfmegkvjujvza",
"oiwcddbseqhxryfingktnujvza",
"oiwcdpbsiqhiryfmlgktnucvza",
"oiwcipbseqhxrkfmlgktnuvvza",
"kiwcdpbseqhxryfmlbkonujvza",
"qiwcdhbsedhxryfmlgktnujvza",
"siwcdpbseqhxryfmsgktnujvua",
"oqwcdpbseqhxryfmlyktndjvza",
"oiwcqnbseehxryfmlgktnujvza",
"oiwcdybseqhxryfmlgbtnujvia",
"oiwcdpbsejhxryfdlgktngjvza",
"oawcdpbseqhxrbfmlkktnujvza",
"oilcdpbseqhhrjfmlgktnujvza",
"oibcdpbseqhxryfmngktnucvza",
"niwcdpbseqhxryfmlgkuaujvza",
"oiwcdpbseqhxryfmqgmtnujvha",
"oiwcdpbseqhcryfxlgktnzjvza",
"oiwcdpaseqhxryfmqgktnujvzl",
"oiwcdpbseqhxjyfmlgkonujvzx",
"oiwmdzbseqlxryfmlgktnujvza",
"oiwhdpbsexhxryfmlgktnujvzw",
"oiwctpbseqhxryfmlgktnummza",
"oiwcdpbseqoxrydmlgktnujvoa",
"oiwkdpvseqhxeyfmlgktnujvza",
"oixcdpbsemhxryfmlgctnujvza",
"oimcdpbseqhxryfmlgktnujvlr",
"oiwcdpbseehxrywmlgktnejvza",
"oiwcdpbseqoxhyfmlgktnujyza",
"oiwcdpbsethxryfmlgktnrjvxa",
"oiwcdpbxeqhxryfmlgktnrjvzb",
"ogeadpbseqhxryfmlgktnujvza",
"eiwcdpbseqhxryfmlgktnvuvza",
"oiwcdpbseqhxryfmlgktnujaxv",
"siwcdpbsuqhxryfmlgktnuavza",
"oixcdpbseqhxryfmlgatnujvzy",
"oiwcdpbzeghmryfmlgktnujvza",
"oiwcdpbieqhxryfmlgktyujvzr",
"oiwcdpbseqhxeyfhlgktngjvza",
"oiwcdpbseqhjoyrmlgktnujvza",
"iiwcdpbseqhxryfmwhktnujvza",
"oixcdpbsiqhxryfmagktnujvza",
"oiwcdpfljqhxryfmlgktnujvza",
"oivcdpbseqhxrqfmlgktnujvca",
"ovwcdpbseqhxzyfmlgkenujvza",
"oiwxdpgseqhxryfmlgktnhjvza",
"oibcdpbbeohxryfmlgktnujvza",
"oiwcrpbseqhxrygmlgwtnujvza",
"jiwcdpbseqkxryfmlgntnujvza",
"oiwcdbbseqhxrywmlgktnujvra",
"oiwcdpbteqyxoyfmlgktnujvza",
"oiwcdjbsvqvxryfmlgktnujvza",
"obwcdukseqhxryfmlgktnujvza",
"oifcdpdseqhxryfmlgktnujsza",
"oiwcdpbseqhxryfalgktnujyda",
"oiwcwpbseqhxrnfmkgktnujvza",
"oswcdpbsethcryfmlgktnujvza",
"oiwcdpbieqhxryfmlgktnuoiza",
"oiwcdibsehhxryfmzgktnujvza",
"oisjdpbseqhxryfmfgktnujvza",
"oiwcjpbseqkxqyfmlgktnujvza",
"obwcdpbshqhgryfmlgktnujvza",
"oiwcspbseqhxryxmlgktnujvzl",
"oiwcdvbswqhxryfmlgklnujvza",
"oiwcdhuseqhxryfmlgdtnujvza",
"oiwcdpbkeqdxryfmlgktnujvzv",
"oiwcdpzseqhxcyfmlgksnujvza",
"oiwcdpbseqhxryfmbkkvnujvza",
"qiwcdpbseqhxrnfmlgktnujvha",
"okwcdpbseqhxryfmdgktgujvza",
"oiwcdpbkeqhxryfmldktnujvzu",
"oiwctpxseqhxgyfmlgktnujvza",
"oiwcdpbseqhxrykmlgktnujita",
"oiwcdpbseqhxryfmldktyujnza",
"oiwcdpbszqhxrjfmlgktnuqvza",
"oiwcdpbeeqhxrykmlgktnujrza",
"oiwcvpbseqhxryhmlgwtnujvza",
"oiwcdpbpeehxryfmlgktnujvzz",
"oiwcdbbsxqhxyyfmlgktnujvza",
"oiwkdpbseqhxryfplgktnujeza",
"opwcdpbseqhxdyfmlgctnujvza",
"oowcdpbseqhnryfmlgktnujvga",
"oawzdibseqhxryfmlgktnujvza",
"oiwcdpbfeqzxrjfmlgktnujvza",
"oiwcdpbseqaxryfmlgkonulvza",
"oiacdpbseqvxryfmlgktvujvza",
"oiwudpbseqhxryfwlgktnujvka",
"oiwcdpbjeqhxryfymgktnujvza",
"oiwcdpbweqhxrynmlgktnujaza",
"oiwcdpbseqdxryfclgvtnujvza",
"oiwcdppseqhxryfmlgmtzujvza",
"oiwcdpbseqhxrhfelektnujvza",
"kiwcdpbsnqhxryfmegktnujvza",
"oiwcdpbseqpxryfmlgzwnujvza",
"eiwcdpbseqnxryfplgktnujvza",
"oiwcdbbseqhxryfmlmktnujvha",
"oiwcdpbseqhxryfmlgktjhjvka",
"oiwcdpbseqhxnyfylgktnujvzs",
"oiwcdpbbxqhxryfmzgktnujvza",
"opwcdpbseqhfryfmlgktnujzza",
"oiwcdpbsjqpxryfmtgktnujvza",
"oiwcdpbseqhyqbfmlgktnujvza",
"oxwcdpbseqhxrffmlgktiujvza",
"oiwcdpbseqhxgyfmlgytnujvzq",
"oiwidpbseqhxryfmlgxtnujvzd",
"oiwcdpbshqhxryzmlpktnujvza",
"oifcdpbseqbxryfmlgktdujvza",
"biwcdzbseqhxtyfmlgktnujvza",
"oiwcdpbswqhxryfmlgutnujvca",
"xiwcdpbseqhxryxmlnktnujvza",
"oiwcdpzseqhxryfrlgktdujvza",
"oiwudpbseqhxryfmlgkqnurvza",
"oiwqdpbseihiryfmlgktnujvza",
"iiwjdpbseqhxryamlgktnujvza",
"oiwcdplseqhqryfmmgktnujvza",
"oiwcdppseqhxrmfmlgklnujvza",
"oiwcdobseqhxryfmmgkttujvza",
"odwcdpbseqhxryfmlgktnujvyk",
"oiwcdpkseqhxrhfmlgktntjvza",
"oiocdpbseqhxryfmlgjknujvza",
"oiicdpbieqhxryfmlgksnujvza",
"oiwcdpbseqhxryemlgktnujdla",
"oiwcdpbseqdxryfmlgktsujvzt",
"oiwcdcksnqhxryfmlgktnujvza",
"oowcdpbseqhxryfmlgsfnujvza",
"oawcdpbseqhxryfmljktnuevza",
"oiwcdpbsaqhxrffmzgktnujvza",
"oiwcipbseqhcryfmlgktnujvga",
"oiwcdpbsewhxrbfmlgktnuuvza",
"oiwcdpbsewhxryfmlgkunujvzc",
"oiwcdpbseqhxryfmlgktiujkga",
"jiwcdpbseqhxrlfmlgktnurvza",
"tiwcdpbseqoxryfmliktnujvza",
"oiwcdpbsenhxryfmlgkskujvza",
"oiwcdpbseqhxvyfmlhktoujvza",
"oiwcdpbseqhxeyfmlgmtnunvza",
"oiwcdpbseqhxdyfmloktnujvzu",
"oiwcdpbseqgxryfmlgkynejvza",
"oudcdpbseqhxryfmlgktmujvza",
"oiwcdpbseqhxryfmvgktnucvzc",
"oiwcdpbseqhxrysalgwtnujvza",
"odwodpbseqhgryfmlgktnujvza",
"oiwcdpbseqheryzmlgktnujgza",
"oiwcdpbseqhxryfalgwtnujvba",
"oiwcdpbseqhxryfmlgtdnuhvza",
"oiocdpbseqhxrefulgktnujvza",
"kiwcdpbseqhxrywolgktnujvza",
"niwcdpbseksxryfmlgktnujvza",
"oiwcdybseqexryfalgktnujvza",
"oiwcdpbbeqhxryamlgktnujpza",
"oiecdqbseqhxryfmlgktnujcza",
"oiwcdpbsqqhxlyfmlpktnujvza",
"oiwcdpbsaqheryfmlgktnujlza",
"oiecdpbseqhxryfmlgkknujvzz",
"oiwcapbsdqhxryfmlgktvujvza",
"ojwcdxbseqhxryfmlgktrujvza",
"oiwhdpbseqvxrzfmlgktnujvza",
"oiwcdppseqhtryfmlgktnujvzs",
"oikcdpbsfqhxryfmdgktnujvza",
"owwczpbseqhxryfilgktnujvza",
"oifwdpbseqhxryfmlgktnujfza",
"oowcdpbseqhxrprmlgktnujvza",
"oiwcapbseqhxryfmjgktnujvze",
"oiwcdpaseqhdrybmlgktnujvza",
"tiwcdpbseqhxryfmlgkvjujvza",
"xiwcdpbseqhoryfmlgktnujvqa",
"eiwrdpbsyqhxryfmlgktnujvza",
"oiwcdpbseqhxranmlgktnujvzt",
"oiwcdpbseqhxryfqlgktnudaza",
"oiwcdpbsvqhxrywmlgktnsjvza",
"oewcdpbseqhxryfmlgkunujvma",
"oiwcdpbseqhjrywmlgktnujvzb",
"omwcdpbseqhxryfmlgktwujsza",
"oiwcdpbyxqhxryfmlgrtnujvza",
"oiwidpbseqhxryfhlgktnunvza",
"oqwcdpbweqhxrybmlgktnujvza",
"oiwcdqbseqhxryfrlgktnujfza",
"oiacdpbseqhdryfmlgktaujvza",
"oiwcdpbstqhxmyfmlgktyujvza",
"oiwcdpbseqhxeyfclgktjujvza",
"wiwcdpeseqhxryfmlgktnujvzx",
"viwcdpbseqhxryfmlgvtvujvza",
"oircdpbseqhxcyfmlgktnujvma",
"miwcdpbseqtwryfmlgktnujvza",
"oiwcppbseqhxcyfmlgxtnujvza",
"giwcrpbseqhxryfmlgktnudvza",
"onwcvpbseqhxryfmlgktnujqza",
"oiwcipbseqhxryfmlgitnuqvza",
"oiwcdpbseqhxryjmlgkonufvza",
"oiwnwpbseqhxtyfmlgktnujvza",
"oiwcypbseqhxryfmlgetnujvzv",
"oiwcdpbseqhxryqmljktnkjvza",
"olwcdpbseqhxryfmlgkenujvba",
"biwcdpbseqwxrywmlgktnujvza",
"oiwcdpbsevhmryjmlgktnujvza",
"oiwcdpbseqhxryfmlzktnkjvzv",
"oiwudpbseqhxrefmlgktnujvia",
"oiicdpbseqhxryfdloktnujvza",
"oihcjpbsxqhxryfmlgktnujvza",
        };
    }
}
